export const products = [
  // {
  //     id: '1',
  //     img: 'https://m.media-amazon.com/images/I/61HVwBtUb9L._SX522_.jpg',
  //     name: 'D-fix® 1PCS Amazon Branded Prime Printed Tape 65 Meter Length, 72mm, (3-inch Width) Very Strong Self Adhesive',
  //     desc: ['[SIZE] Excellent adhesive, simple to use over the entire 65 metres, and the ideal size for 3-inch tape dispensers.', '[DURABLE] The best stands for heat, humidity, and cold have a high quality and long shelf life. These temperature resistant tapes are extensively famous for their durability and excellent adhesive strength.', '[USES] It Can Be Used for Packing Shipping or Mailing Boxes, Courier, Online E-Commerce Orders, House Use, Many More Uses.'],
  //     mrp: 95,
  //     discount: 0.3,
  //     quantity: 10,
  //     gst: 0.16,
  //     details: {brand: 'xyz', color: 'black', material: ''},
  //     counterNum: 10,
  // },
  // {
  //     id: '2',
  //     img: 'https://m.media-amazon.com/images/I/61hkny3XELL._SX679_.jpg',
  //     name: 'Presto! Spin Mop, Oval Bucket with Plastic Basket, 2 Refills',
  //     desc: ['[SIZE] Excellent adhesive, simple to use over the entire 65 metres, and the ideal size for 3-inch tape dispensers.', '[DURABLE] The best stands for heat, humidity, and cold have a high quality and long shelf life. These temperature resistant tapes are extensively famous for their durability and excellent adhesive strength.', '[USES] It Can Be Used for Packing Shipping or Mailing Boxes, Courier, Online E-Commerce Orders, House Use, Many More Uses.'],
  //     mrp: 1900,
  //     discount: 0.3,
  //     quantity: 50,
  //     gst: 0.16,
  //     details: {brand: 'xyz', color: 'black', material: ''},
  //     counterNum: 5,
  // },
  // {
  //     id: '3',
  //     img: 'https://m.media-amazon.com/images/I/51c3SBvGWmL._SX300_SY300_QL70_FMwebp_.jpg',
  //     name: 'Scotch-Brite Sponge Wipe Resusable Kitchen Cleaning Sponge- Easy to use, Multi- color & Biodegradable (pack of 3)',
  //     desc: ['[SIZE] Excellent adhesive, simple to use over the entire 65 metres, and the ideal size for 3-inch tape dispensers.', '[DURABLE] The best stands for heat, humidity, and cold have a high quality and long shelf life. These temperature resistant tapes are extensively famous for their durability and excellent adhesive strength.', '[USES] It Can Be Used for Packing Shipping or Mailing Boxes, Courier, Online E-Commerce Orders, House Use, Many More Uses.'],
  //     mrp: 95,
  //     discount: 0.3,
  //     quantity: 10,
  //     gst: 0.16,
  //     details: {brand: 'xyz', color: 'black', material: ''},
  //     counterNum: 10,
  // }

  {
    name: "Apple",
    price: 1.2,
    category: "Fruits",
    image_link: "https://example.com/images/apple.jpg",
    gst: 0.05,
    description: "Fresh and juicy apples. Perfect for a healthy snack.",
    discount: 0.1,
    total_price: 1.2 + 1.2 * 0.05 - 1.2 * 0.1,
    quantity: 50,
  },
  {
    name: "Banana",
    price: 0.8,
    category: "Fruits",
    image_link: "https://example.com/images/banana.jpg",
    gst: 0.05,
    description: "Sweet and ripe bananas. Great for smoothies.",
    discount: 0.1,
    total_price: 0.8 + 0.8 * 0.05 - 0.8 * 0.1,
    quantity: 100,
  },
  {
    name: "Orange",
    price: 1.0,
    category: "Fruits",
    image_link: "https://example.com/images/orange.jpg",
    gst: 0.05,
    description: "Fresh and juicy oranges. High in Vitamin C.",
    discount: 0.1,
    total_price: 1.0 + 1.0 * 0.05 - 1.0 * 0.1,
    quantity: 75,
  },
  {
    name: "Bread",
    price: 2.5,
    category: "Bakery",
    image_link: "https://example.com/images/bread.jpg",
    gst: 0.1,
    description: "Soft and fresh whole grain bread. Perfect for sandwiches.",
    discount: 0.15,
    total_price: 2.5 + 2.5 * 0.1 - 2.5 * 0.15,
    quantity: 30,
  },
  {
    name: "Cake",
    price: 15.0,
    category: "Bakery",
    image_link: "https://example.com/images/cake.jpg",
    gst: 0.1,
    description: "Delicious and moist chocolate cake. Great for celebrations.",
    discount: 0.2,
    total_price: 15.0 + 15.0 * 0.1 - 15.0 * 0.2,
    quantity: 10,
  },
  {
    name: "Cookies",
    price: 3.5,
    category: "Bakery",
    image_link: "https://example.com/images/cookies.jpg",
    gst: 0.1,
    description:
      "Crunchy and sweet chocolate chip cookies. Perfect with a cup of tea.",
    discount: 0.15,
    total_price: 3.5 + 3.5 * 0.1 - 3.5 * 0.15,
    quantity: 20,
  },
  {
    name: "Milk",
    price: 1.7,
    category: "Dairy",
    image_link: "https://example.com/images/milk.jpg",
    gst: 0.06,
    description: "Fresh whole milk. High in calcium and protein.",
    discount: 0.1,
    total_price: 1.7 + 1.7 * 0.06 - 1.7 * 0.1,
    quantity: 100,
  },
  {
    name: "Cheese",
    price: 5.0,
    category: "Dairy",
    image_link: "https://example.com/images/cheese.jpg",
    gst: 0.06,
    description:
      "Creamy and delicious cheddar cheese. Great for sandwiches and pizzas.",
    discount: 0.1,
    total_price: 5.0 + 5.0 * 0.06 - 5.0 * 0.1,
    quantity: 50,
  },
  {
    name: "Yogurt",
    price: 2.0,
    category: "Dairy",
    image_link: "https://example.com/images/yogurt.jpg",
    gst: 0.06,
    description:
      "Smooth and creamy plain yogurt. Perfect for breakfast and snacks.",
    discount: 0.1,
    total_price: 2.0 + 2.0 * 0.06 - 2.0 * 0.1,
    quantity: 80,
  },
];
